name: Build APKKiller APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Set up NDK (for JNI/native code)
      uses: android-actions/setup-ndk@v1
      with:
        ndk-version: '25.1.8937393'  # Adjust to your NDK version

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew || chmod +x ./app/gradlew  # Adjust path if needed

    - name: Build Debug APK
      run: ./gradlew assembleDebug  # Or ./gradlew assembleRelease for signed

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: APKKiller-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk  # Adjust path if needed
